###
GET http://localhost:8080/api/dances

###
POST http://localhost:8080/api/dances
Content-Type: application/json

{
  "name": "Sevillanas",
  "region": "Andalucia",
  "description": "Baile tradicional andaluz"
}

###
DELETE http://localhost:8080/api/dances/1

###
DELETE http://localhost:8080/api/dances/all

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "user3",
  "password": "password123"
}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "defrfr",
  "username": "user3",
  "password": "password123",
  "dateOfBirth": "2004-11-29"
}